### ISSUE TITLE
Crash while breaking the device fissure

### ISSUE THREAD

**Issue by Davoleo** [HellFirePvP/Fracture#1]
I don't know if you're accepting issues, but I'll post it here...
Forge Version: 2654
Fracture Version: 0.2
Steps to reproduce: place a three blocks high device fissure > what for it to make blocks translucent > break some blocks > break the pillar
[crash log](https://paste.ee/p/4NO1T)

**Comment by HellFirePvP** [comment]
There was a reason i made those videos and made page-long instructions. And there is a reason this mod is NOT published and only available if you're literally face-first looking at the instructions and be like "ouh, yea, i just want the mod, let's ignore everything else"
